name: My First Job

on: push

jobs:

  job-1:
    runs-on: ubuntu-latest
    steps:
    - name: Printing HelloWord
      run: echo "HelloWorld"
    - name: checkout the code
      uses: actions/checkout@v4
    - name: Listing Files
      run: ls -la
