name: My First Job

on: push

jobs:

  job-1:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the code
      uses: actions/checkout@main
    - name: Printing HelloWord
      run: echo "HelloWorld"
    - name: Listing Files
      run: ls -la
    - name: Nginx Version Check
      run: nginx -v
    - name: Node Version Check
      run: node -v
