name: Kubernetes Installation
on: push
jobs:
  kubernetes:
    runs-on: ubuntu-latest
    steps:
    - name: Update ubuntu
      run: sudo apt-get update
    - name: Update Certificates on ubuntu
      run: sudo apt-get install -y ca-certificates curl
    - name: Download Kubernetes
      run: curl -LO "https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - name: Update Permissions
      run: chmod +x kubectl
    - name: Move Binary
      run: sudo mv kubectl /usr/local/bin/
    - name: Version Check of Kubernetes
      run: kubectl version --client
