name: Multiple Jobs
on: push
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: echo "Building the Code"
  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: echo "Testing the Code"
  deploy-job:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      run: echo "Deploying the Code"
