name: Multiple Jobs
on: push
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: echo "Building the Code"
    - name: Create a File
      run: touch playwright.txt
    - name: Add Content to playwright file
      run: echo "This is playwright" >> playwright.txt
  test-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: echo "Testing the Code"
    - name: Check Existance of playwright file
      run: if [ -e playwright.txt ]; then echo "Playwright File Exists"; fi
  deploy-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      run: echo "Deploying the Code"
    - name: Read from playwright file
      run: cat playwright.txt
