name: Shell Script
on: push
jobs:
  shell-job:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      run: actions/checkout@main
    - name: List Files
      run: ls -ltra
    - name: Run Shell Script
      run: |
        chmod +x k8.sh
        ./k8.sh
